name: CI

on: 
  push:
  fork:

jobs:
  badges:
    name: Clean ipynb
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: setup environment
      id: setup
      run: python -m pip install bs4 jupyter lxml

    - name: Add/Update badges
      id: badges
      run: python ./utils/add_colab_main_buttons.py

    - name: Commit & push
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message : Add Github badges or remove ipynb `id`s

  test_ipynb_colab:
    needs: badges
    name: test ipynb on Google Colab
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.16'

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Create venv
      run: python -m venv venv

    - name: Activate venv
      run: source venv/bin/activate

    - name: Cache venv
      uses: actions/cache@v3
      with:
        path: venv
        key: ${{ runner.os }}-${{ hashFiles('./requirements.txt') }}

    - name: install dependencies
      run: python -m pip install -r ./requirements.txt

    - name: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: python -m pytest -n auto ./tests
